config/routes.rb
ShopifyAramex::Application.routes.draw do

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  root :to => 'home#index'

  resources :users
  get 'update-shopify-info', to: "users#update_shopify_info", as: "update_shopify_info"
  get 'users/default_domestic_product/json', to: 'users#default_domestic_product', as: "default_domestic_product"
  get 'users/default_express_product/json', to: 'users#default_express_product', as: "default_express_product"
  get 'users/default_domestic_services/json', to: 'users#default_domestic_services', as: "default_domestic_services"
  get 'users/default_express_services/json', to: 'users#default_express_services', as: "default_express_services"

  resources :shipments
  get 'select_shipment_type', to: "shipments#select_shipment_type", as: "select_shipment_type"
  get 'print-label/:shipment_store_id', to: "shipments#print_label", as: "print_label"
  get 'order_by_number', to: "shipments#search_by_order_number", as: "order_by_number"
  
  resources :pickups, only: [:index, :new, :create] 
  get 'pickups/aramex_country_code/', to: 'pickups#aramex_country_code', as: "aramex_country_code"
  get 'pickups/aramex_address_validate/json', to: 'pickups#aramex_address_validate', as: "aramex_address_validate"
  get 'pickups/aramex_country_city/json', to: 'pickups#aramex_country_city',  as: "aramex_country_city"

  
  get 'track/:shipment_store_id', to: "trackings#show", as: "track_shipment"
  get 'tracks', to: "trackings#index", as: "tracks"

  get 'rate-calculator/select-shipment-type', to: "rate_calculator#select_shipment_type", as: "rate_calculator_shipment_type"
  get 'rate-calculator/new', to: "rate_calculator#new", as: "new_rate_calculator"
  post 'rate-calculator/post', to: "rate_calculator#create", as: "post_rate_calculator"

  get 'orders', to: "orders#show"

  get 'search-by-order-number', to: "orders#search_by_order_number"
  get 'search-by-awb', to: "orders#search_by_awb"
  get 'search-by-fullfil', to: "orders#search_by_fullfil"

  
  post 'checkout', to: "checkout#start", as: "checkout"
  post 'webhook', to: "webhook#start", as: "webhook"

  post 'webhook-customers-redact', to: "webhookcustomersredact#start", as: "webhookcustomersredact"
  post 'webhook-shop-redact', to: "webhookshopredact#start", as: "webhookshopredact"
  post 'webhook-customers-data-request', to: "webhookcustomersdatarequest#start", as: "webhookcustomersdatarequest"

  get 'serchautocity', to: "serchautocity#start", as: "serchautocity"
  post 'apilocationvalidator', to: "apilocationvalidator#start", as: "apilocationvalidator"
  get "pages/new" => "new#show"
  get "pages/support" => "support#show"
  get "pages/manual" => "manual#show"
  get "rules" => "rules#show"
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  # Do we need a
  before_filter :valid_shopify_session, :logged_in_user, :except => [:index] 

  # This is Shopify's filter for controlling auth
  around_filter :shopify_session
  
  # The index method for the root_url
  def index
    # Get latest 25 orders - latest order first 
    # @return [Array<Hash>] Latest orders from Shopify API
    # Rails.logger.info "A line before orders"
	#
	#abort current_user.inspect


	# NEW carrier_services
	
	uuu = ShopifyAPI::Webhook.create(address: "https://shopify.aramex.com/webhook", topic: "app/uninstalled", format: "json")
	#	logger.info "#{Time.now} Found user webhook111 #{uuu.inspect}"
	
	
	#	require 'uri'
	#	require 'net/http'
	#	require "json"


	# GET carrier_services
	#	uri = URI.parse("https://" + shop_session.url + "/admin/webhooks.json")
	#	response = Net::HTTP.new(uri.host, uri.port)
	#	http = Net::HTTP.new(uri.host, uri.port)
		#http.use_ssl = true
	#	http.verify_mode = OpenSSL::SSL::VERIFY_NONE
	#	request = Net::HTTP::Get.new(uri.path, initheader = {'Content-Type' =>'application/json', 'X-Shopify-Access-Token' => shop_session.token})
	#	http.request(request)
	#	response = http.request(request)
	#	@parsed_json = JSON.parse(response.body)

	#logger.info @parsed_json.inspect
	
	

	
	
    @orders   = ShopifyAPI::Order.find(:all, :params => {:limit => 25, :order => "created_at DESC" })
    # Rails.logger.info "A line after orders"
  end  
end

app/helpers/home_helper.rb
module HomeHelper

end

app/views/home/index.html.erb
<div class="row">

  <div class="span11 offset1">
    <div id="index_top">
      <%= link_to "Schedule Pickup", new_pickup_path, class: "btn" %>
    </div>

    <div class="search-container">
      <h2>Search By Order Number</h2>
      <form method="get" action="search-by-order-number">
        <input type="text" id="search_by_order_number" name="order_number">
        <input type="submit" value="Search" class="btn btn-primary" >
      </form>
    </div>

    <div class="search-container">
      <h2>Search By Waybill Number</h2>
      <form method="get" action="search-by-awb">
        <input type="text" id="search_by_awb" name="awb">
        <input type="submit" value="Search" class="btn btn-primary" >
      </form>
    </div>

    <div class="search-container">
      <h2>Search By Fulfillment Status</h2>
      <form method="get" action="search-by-fullfil">
		<select id="search_by_fullfil" name="fulfilled">
			<option></option>		
			<option value="ful">Fulfilled</option>
			<option value="unful">Not Fulfilled</option>
			<option value="all">All</option>
		</select>
        <input type="submit" value="Search" class="btn btn-primary" >
      </form>
    </div>
	
    <h2>Recent orders</h2>

    <% if @orders.blank? %>
      <table class="table table-striped">
        <tr>
          <td><em>There are no orders in your store.</em></td>
        </tr>
      </table>

    <% else %>
	    <% if current_user.nil?  %>
			<p style="color:red;">Aramex "account" has not created yet. You should fill in 'Account Information' page and push "Submit" button.</p>

		<% else %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Order </th>
            <th>Placed by</th>
            <th>Paid</th>
            <th>Fulfillment</th>
            <th></th>
          </tr>
        </thead>
		
      <% @orders.each do |order| %>
	  

	  

		
		
		<% if defined?(params[:fulfilled]) and params[:fulfilled] == "ful" %>
		<% if order.fulfillment_status %>
        <tr>
          <td><%= link_to order.name, orders_path(shop: current_user.shop_url, id: order.id ) %></td>
          <td><%= order.billing_address.name unless order %></td>
          <td>
            <span class="label  <% if order.financial_status  == 'paid' %>label-success<% end %> <% if order.financial_status  == 'pending' %>label-warning<% end %> <% if order.financial_status  == 'refunded' %>label-important<% end %>"><%= order.financial_status %>
            </span>
          </td>
          <td>
            <% if !order.fulfillment_status %>
            <span class="label">Not Fulfilled</span>
            <% else %>
            <span class="label label-success">Fulfilled</span>
            <% end %>
          </td>

          <td id="homepage_button_container">

          <% shipment_store = ShipmentStore.find_by_order_id order.id  %>
            <% if shipment_store.nil? %>
              <%= link_to "Create Shipment", select_shipment_type_path(order_id: order.id), class: "btn btn-primary" %>
              <%= link_to "Calculate Rate", rate_calculator_shipment_type_path(order_id: order.id), class: "btn"%>
            <% else %>
              <!-- These 2 options should only come for orders which have an entry in shipment_store -->
              <%= link_to "Print Label", print_label_path(shipment_store_id: shipment_store.id), target: "_blank", class: "btn"%>
              <%= link_to "Track Shipment", track_shipment_path(shipment_store_id: shipment_store.id), class: "btn"%>
              <%= link_to "Calculate Rate", rate_calculator_shipment_type_path(order_id: order.id), class: "btn"%>
            <% end %>
          </td>
        </tr>	
		<% end %>
		
		
		<% elsif defined?(params[:fulfilled]) and params[:fulfilled] == "unful" %>
		<% if !order.fulfillment_status %>
        <tr>
          <td><%= link_to order.name, orders_path(shop: current_user.shop_url, id: order.id ) %></td>
          <td><%= order.billing_address.name unless order %></td>
          <td>
            <span class="label  <% if order.financial_status  == 'paid' %>label-success<% end %> <% if order.financial_status  == 'pending' %>label-warning<% end %> <% if order.financial_status  == 'refunded' %>label-important<% end %>"><%= order.financial_status %>
            </span>
          </td>
          <td>
            <% if !order.fulfillment_status %>
            <span class="label">Not Fulfilled</span>
            <% else %>
            <span class="label label-success">Fulfilled</span>
            <% end %>
          </td>

          <td id="homepage_button_container">

          <% shipment_store = ShipmentStore.find_by_order_id order.id  %>
            <% if shipment_store.nil? %>
              <%= link_to "Create Shipment", select_shipment_type_path(order_id: order.id), class: "btn btn-primary" %>
              <%= link_to "Calculate Rate", rate_calculator_shipment_type_path(order_id: order.id), class: "btn"%>
            <% else %>
              <!-- These 2 options should only come for orders which have an entry in shipment_store -->
              <%= link_to "Print Label", print_label_path(shipment_store_id: shipment_store.id), target: "_blank", class: "btn"%>
              <%= link_to "Track Shipment", track_shipment_path(shipment_store_id: shipment_store.id), class: "btn"%>
              <%= link_to "Calculate Rate", rate_calculator_shipment_type_path(order_id: order.id), class: "btn"%>
            <% end %>
          </td>
        </tr>	
		<% end %>
		<% else %>
		
		
		
		
        <tr>
          <td><%= link_to order.name, orders_path(shop: current_user.shop_url, id: order.id ) %></td>
          <td><%= order.billing_address.name unless order %></td>
          <td>
            <span class="label  <% if order.financial_status  == 'paid' %>label-success<% end %> <% if order.financial_status  == 'pending' %>label-warning<% end %> <% if order.financial_status  == 'refunded' %>label-important<% end %>"><%= order.financial_status %>
            </span>
          </td>
          <td>
            <% if !order.fulfillment_status %>
            <span class="label">Not Fulfilled</span>
            <% else %>
            <span class="label label-success">Fulfilled</span>
            <% end %>
          </td>

          <td id="homepage_button_container">

          <% shipment_store = ShipmentStore.find_by_order_id order.id  %>
            <% if shipment_store.nil? %>
              <%= link_to "Create Shipment", select_shipment_type_path(order_id: order.id), class: "btn btn-primary" %>
              <%= link_to "Calculate Rate", rate_calculator_shipment_type_path(order_id: order.id), class: "btn"%>
            <% else %>
              <!-- These 2 options should only come for orders which have an entry in shipment_store -->
              <%= link_to "Print Label", print_label_path(shipment_store_id: shipment_store.id), target: "_blank", class: "btn"%>
              <%= link_to "Track Shipment", track_shipment_path(shipment_store_id: shipment_store.id), class: "btn"%>
              <%= link_to "Calculate Rate", rate_calculator_shipment_type_path(order_id: order.id), class: "btn"%>
            <% end %>
          </td>
        </tr>	



		
		<% end %>
		
		
      <% end %>
      </table>

	        <% end %>
	  
	  
    <% end %>

    <br/>

  </div> <!-- span8 / right-column -->

</div>