config/routes.rb
ShopifyAramex::Application.routes.draw do

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  root :to => 'home#index'

  resources :users
  get 'update-shopify-info', to: "users#update_shopify_info", as: "update_shopify_info"
  get 'users/default_domestic_product/json', to: 'users#default_domestic_product', as: "default_domestic_product"
  get 'users/default_express_product/json', to: 'users#default_express_product', as: "default_express_product"
  get 'users/default_domestic_services/json', to: 'users#default_domestic_services', as: "default_domestic_services"
  get 'users/default_express_services/json', to: 'users#default_express_services', as: "default_express_services"

  resources :shipments
  get 'select_shipment_type', to: "shipments#select_shipment_type", as: "select_shipment_type"
  get 'print-label/:shipment_store_id', to: "shipments#print_label", as: "print_label"
  get 'order_by_number', to: "shipments#search_by_order_number", as: "order_by_number"
  
  resources :pickups, only: [:index, :new, :create] 
  get 'pickups/aramex_country_code/', to: 'pickups#aramex_country_code', as: "aramex_country_code"
  get 'pickups/aramex_address_validate/json', to: 'pickups#aramex_address_validate', as: "aramex_address_validate"
  get 'pickups/aramex_country_city/json', to: 'pickups#aramex_country_city',  as: "aramex_country_city"

  
  get 'track/:shipment_store_id', to: "trackings#show", as: "track_shipment"
  get 'tracks', to: "trackings#index", as: "tracks"

  get 'rate-calculator/select-shipment-type', to: "rate_calculator#select_shipment_type", as: "rate_calculator_shipment_type"
  get 'rate-calculator/new', to: "rate_calculator#new", as: "new_rate_calculator"
  post 'rate-calculator/post', to: "rate_calculator#create", as: "post_rate_calculator"

  get 'orders', to: "orders#show"

  get 'search-by-order-number', to: "orders#search_by_order_number"
  get 'search-by-awb', to: "orders#search_by_awb"
  get 'search-by-fullfil', to: "orders#search_by_fullfil"

  
  post 'checkout', to: "checkout#start", as: "checkout"
  post 'webhook', to: "webhook#start", as: "webhook"

  post 'webhook-customers-redact', to: "webhookcustomersredact#start", as: "webhookcustomersredact"
  post 'webhook-shop-redact', to: "webhookshopredact#start", as: "webhookshopredact"
  post 'webhook-customers-data-request', to: "webhookcustomersdatarequest#start", as: "webhookcustomersdatarequest"

  get 'serchautocity', to: "serchautocity#start", as: "serchautocity"
  post 'apilocationvalidator', to: "apilocationvalidator#start", as: "apilocationvalidator"
  get "pages/new" => "new#show"
  get "pages/support" => "support#show"
  get "pages/manual" => "manual#show"
  get "rules" => "rules#show"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <title><%= full_title(yield(:title)) %></title>




        <!-- Bootstrap CSS -->




 
  <link rel="shortcut icon" href="../assets/favicon.png">
  <link rel="apple-touch-icon" href="../assets/shopify-57.png">
  <link rel="apple-touch-icon" sizes="72x72" href="../assets/shopify-72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="../assets/shopify-114.png">


   <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
        <!--<link rel="stylesheet" href="build/css/intlTelInput.css">-->
        
<%= stylesheet_link_tag 'application' %>
<%= javascript_include_tag 'application' %>
</head>
<!--

<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application' %>

  <%= javascript_include_tag 'application' %>
  
  
  <%= csrf_meta_tags %>
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

  <link rel="shortcut icon" href="../assets/favicon.png">
  <link rel="apple-touch-icon" href="../assets/shopify-57.png">
  <link rel="apple-touch-icon" sizes="72x72" href="../assets/shopify-72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="../assets/shopify-114.png">

</head>
 -->

<body>
        <nav class="navbar fixed-top flex-md-nowrap p-0">
              <%= image_tag 'small-logo.png', :class => "small-logo", :alt => "Aramex" %> <p>aramex shipping service app</p>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <nav class=" bg-light sidebar">
                    <div class="sidebar-sticky">
                        <%= image_tag 'aramex-logo.png', :class => "aramex logo", :alt => "Aramex Logo" %> 
                        <ul class="menu-left">
                            <% if controller?("shipments") && action?("new") %>
                              <li class="active">
                            <% else %>
                              <li>
                            <% end %>
                                <%= link_to raw('Create shipment'), "http://localhost:3000/shipments/new" %>
                            </li>
                            <% if controller?("pickups") && action?("new") %>
                              <li class="active">
                            <% else %>
                              <li>
                            <% end %>
                                <%= link_to raw('Create Pickup'), "http://localhost:3000/pickups/new" %>
                            </li>
                            <% if controller?("shipments") && action?("index") %>
                              <li class="active">
                            <% else %>
                              <li>
                            <% end %>
                                <%= link_to raw('Shipments'), "http://localhost:3000/shipments" %>
                            </li>       
                            <% if controller?("pickups") && action?("index") %>
                              <li class="active">
                            <% else %>
                              <li>
                            <% end %>
                                <%= link_to raw('Pickups'), "http://localhost:3000/pickups" %>
                            </li>   
                            <% if controller?("trackings") && action?("index") %>
                              <li class="active">
                            <% else %>
                              <li>
                            <% end %>
                              <%= link_to raw('Tracking'), "http://localhost:3000/tracks" %>
                            </li>  
                            <% if controller?("users") && action?("edit") %>
                              <li class="active">
                            <% else %>
                              <li>
                            <% end %>
                              <%= link_to raw('Settings'), "http://localhost:3000/users/"+current_user.id.to_s+"/edit" %>
                            </li> 
                        </ul>


                    </div>
                </nav>



<!--
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">

        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <%= link_to 'Aramex Shopify App', '/', :class => 'brand' %>

        <% if shop_session %>

          <ul class="nav pull-right">

		   
		  
		  
		  <% unless current_user.nil? %>
            <li><%= link_to "Home", root_url %></li>
			<% end %>
            <li class="dropdown">
              <%= link_to raw(shop_session.url+' <b class="caret"></b>'), "https://#{shop_session.url}", :class => 'shop_name dropdown-toggle', :'data-toggle' => 'dropdown', :'data-target' => '#' %>
              <ul class="dropdown-menu">
	 <% 	  
if current_user.nil?  %>
   <li><%= link_to raw('<i class="icon-wrench"></i> Account Information'), "/users/new"  %></li>
<%  end
		   %>
                <% unless current_user.nil? %>
                  <li><%= link_to raw('<i class="icon-wrench"></i> Account Information'), edit_user_path(current_user.id)  %></li>
                <% end %>

                <li><%= link_to raw('<i class="icon-home"></i> Storefront'), "http://"+shop_session.url, :target => 'blank' %></li>
                <li><%= link_to raw('<i class="icon-cog"></i> Shopify Admin'), "http://"+shop_session.url+"/admin", :target => 'blank' %></li>
                <% unless current_user.nil? %>

                  <li><%= link_to raw('<i class="icon-cog"></i> Rate calculator on Checkout page'), request.base_url + "/pages/new", :target => 'blank' %></li>
				  <li><%= link_to raw('<i class="icon-cog"></i> Support'), request.base_url + "/pages/support", :target => 'blank' %></li>
				  <li><%= link_to raw('<i class="icon-cog"></i> Installation/User manual'), request.base_url + "/pages/manual", :target => 'blank' %></li>
                <% end %>
                <li class="divider"></li>
                <li><%= link_to raw('<i class="icon-off"></i> Logout'), logout_path, :method => :delete %></li>
              </ul>
            </li>
          </ul>
        <% end %>

      </div>
    </div>
  </div>


  <div class="container">

    <%= render 'shared/flash_messages' %>

    <div class="content">
      <%#= yield %>
    </div>

    <footer>
      <p>A Shopify app by Aramex</p>
    </footer>

  </div> -->

<main class="main">  
  <%= yield %>
</div> 

        </div>

    </div>
</body>
</html>

app/views/layouts/unauthorized.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <title><%= full_title(yield(:title)) %></title>


   <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
        <!--<link rel="stylesheet" href="build/css/intlTelInput.css">-->
        
<%= stylesheet_link_tag 'application' %>
<%= javascript_include_tag 'application' %>
    </head>

    <body>
        <div class="roww">
          <div class="wave"><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C149.99,150.00 271.49,-49.98 500.00,49.98 L500.00,0.00 L0.00,0.00 Z" style="stroke: none; fill: #DC281E;"></path></svg>
          </div>      
    
        <%= yield %>
        </div>

                    <script>
                    $(document).ready(function () {
                        resizeDiv();

                    $("#amx-1  input").click(function () {
						          $("#user_default_product_group").val($(this).attr("data-type"));
                    });

                    $("#amx-2  button").click(function () {
						          $("#user_default_domestic_services").val($(this).attr("data-type"));
                    });

                    $("#amx-3  input").click(function () {
						          $("#user_default_international_product_type").val($(this).attr("data-type"));
                    });

                    $("#amx-4  button").click(function () {
						          $("#user_default_international_services").val($(this).attr("data-type"));
                    });

                    $("#amx-5  button").click(function () {
						          $("#user_default_prepaid_payment_option").val($(this).attr("data-type"));
                    });

                    window.resize = function (event) {
                        resizeDiv();
                    }

                    function resizeDiv() {
                        $(".roww").css("height", $(document).height() + "px");
                    }
                    function resizeDivInternational() {

                        $(".roww").css("height", $(document).height() +40 + "px");
                    }

                    $("#user_email").focus();
                    var errors = [];

                    $("#user_email").blur(function () {
                        var email = $('#user_email').val();
                        var re = /\S+@\S+\.\S+/;
                        if (email.trim().length == 0) {
                            $('#user_email').next('div.red').remove();
                            $('#user_email').after('<div class="red">\'Email\' is Required</div>');
                            errors.push("email_required");
                            resizeDiv();
                        } else if (!re.test(email)) {
                            $('#user_email').next('div.red').remove();
                            $('#user_email').after('<div class="red">\'Email\' is not correct</div>');
                            errors.push("email_not_valid");
                            resizeDiv();
                        } else {
                            $(this).next('div.red').remove();
                            errors = removeError(errors, "email_required");
                            errors = removeError(errors, "email_not_valid");
                        }
                        makeActive();
                    });

                    $("#user_password").blur(function () {
                        var password = $('#user_password').val();
                        if (password.trim().length == 0) {
                            $('#user_password').next('div.red').remove();
                            $('#user_password').after('<div class="red">\'Password\' is Required</div>');
                            errors.push("password_required");
                            resizeDiv();
                        } else {
                            $('#user_password').next('div.red').remove();
                            errors = removeError(errors, "password_required");
                        }
                        makeActive();
                    });

                    $("#user_account_number").blur(function () {
                        var user_account_number = $('#user_account_number').val();
                        var onlyDigits = /^\d*$/;
                        if (user_account_number.trim().length == 0) {
                            $('#user_account_number').next('div.red').remove();
                            $('#user_account_number').after('<div class="red">\'Account Number\' is Required</div>');
                            errors.push("user_account_number_required");
                            resizeDiv();
                        } else if (!onlyDigits.test(user_account_number)) {
                            $('#user_account_number').next('div.red').remove();
                            $('#user_account_number').after('<div class="red">\'Account Number\' is not correct. Only numbers are allowed.</div>');
                            errors.push("user_account_number_not_valid");
                            resizeDiv();
                        } else {
                            $('#user_account_number').next('div.red').remove();
                            errors = removeError(errors, "user_account_number_required");
                            errors = removeError(errors, "user_account_number_not_valid");
                            resizeDiv();
                        }
                        makeActive();
                    });

                    $("#user_account_pin").blur(function () {
                        var user_account_pin = $('#user_account_pin').val();
                        var onlyDigits = /^\d*$/;
                        if (user_account_pin.trim().length == 0) {
                            $('#user_account_pin').next('div.red').remove();
                            $('#user_account_pin').after('<div class="red">\'Account Pin\' is Required</div>');
                            errors.push("user_account_pin_required");
                            resizeDiv();
                        } else if (!onlyDigits.test(user_account_pin)) {
                            $('#user_account_pin').next('div.red').remove();
                            $('#user_account_pin').after('<div class="red">\'Account Pin\' is not correct. Only numbers are allowed.</div>');
                            errors.push("user_account_pin_not_valid");
                            resizeDiv();
                        } else {
                            $(this).next('div.red').remove();
                            errors = removeError(errors, "user_account_pin_required");
                            errors = removeError(errors, "user_account_pin_not_valid");
                        }
                        makeActive();
                    });

                    function removeError(newArray, removeItem) {
                        var newArray = jQuery.grep(newArray, function (value) {
                            return value != removeItem;
                        });
                        return newArray;
                    }

                    function makeActive() {

                        var empty = false;
                        $('.to-valid').each(function () {
                            if ($(this).val().trim() === "") {
                                 empty = true;
                            }
                        });

                        if (errors.length === 0 && empty === false) {
                            if ($('.big-button').hasClass('passive')) {
                                $('.big-button').removeClass('passive')
                            }

                        } else {
                            if (!$('.big-button').hasClass('passive')) {
                                $('.big-button').addClass('passive')
                            }
                        }
                    }

					$('.big-button').click(function() {
   						if (!$(this).hasClass('passive')) {
                           $('.step1').hide();
                           $('.step2').fadeIn("slow")
                        }
    				});


					$('#productGroup').click(function() {
						if(!$(this).hasClass("grey-button-border")){
							resizeDivInternational();
						}
              $('.international').hide();
              $('.domestic').fadeIn("slow")
              $('#amx-1').fadeIn("slow")
              $('.button-block-pair').removeClass('button-top-bottom')                   
    				});

            $('#amx-1').click(function() {
              $('#amx-2').fadeIn("slow")  
            });

            $('#productType').click(function() {
              if(!$(this).hasClass("grey-button-border")){
                resizeDivInternational();
              }
              $('.domestic').hide();
              $('.international').fadeIn("slow")
              $('#amx-3').fadeIn("slow")
              $('.button-block-pair').removeClass('button-top-bottom')   
            });
          
            
            
            $('#productGroup').click(function() {
              $('#user_default_product_group').val('DOM')
        
            })
            $('#productType').click(function() {
              $('#user_default_product_group').val('EXP')            
            })
            $('#economyParcel').click(function () {
              $('#user_default_domestic_product_type').val('EPX')
            })
            $('#priorityParcel').click(function () {
              $('#user_default_domestic_product_type').val('PPX')
            })
            $('#ecommerceParcel').click(function () {
              $('#user_default_domestic_product_type').val('CDS')
            })
            $('#cashOnDelivery').click(function () {
              $('#user_default_domestic_services').val('CODS')
            })
            $('#prepaid').click(function () {
              $('#user_default_domestic_services').val('P')
            })
            $('#economyParcelInt').click(function () {
              $('#user_default_international_product_type').val('EPX')
            })
            $('#priorityParcelInt').click(function () {
              $('#user_default_international_product_type').val('PPX')
            })
            $('#ecommerceParcelInt').click(function () {
              $('#user_default_international_product_type').val('CDS')
            })
            $('#cashOnDeliveryInt').click(function () {
              $('#user_default_international_services').val('CODS')
            })
            $('#prepaidInt').click(function () {
              $('#user_default_international_services').val('P')
            })
            $('#deliveryDutyUnpaidInt').click(function () {
              $('#user_default_prepaid_payment_option').val('DDU')
            })
            $('#deliveryDutyPaidInt').click(function () {
              $('#user_default_prepaid_payment_option').val('DDP')
            })

           
            $('#amx-3').click(function() {
                $('#amx-4').fadeIn("slow")
                
            });
            $('#amx-4').click(function() {
                $('#amx-5').fadeIn("slow")
                
            });

 					var validErrors = [];

    				$('.grey-button').click(function() {
		                    $(this).closest('.aramex-input-block2').find(".grey-button").removeClass('grey-button-border')
		                    $(this).addClass('grey-button-border')

		                    if(typeof $(this).closest('.aramex-input-block2').attr('id') !== "undefined")
								{
  									validErrors = checkAllSelected($(this).closest('.aramex-input-block2').attr('id'));
								} 

    				});	

                    function checkAllSelected(removeItem) {

                        var newArray = jQuery.grep(validErrors, function (value) {
                            return value != removeItem;
                        });
                        newArray.push(removeItem);

                        if(newArray.length === 5){
                        	$('.button-done').removeClass('passive')
                        }
                        return newArray;
                    }

    				$('.button-back').click(function() {
		                    $('.step2').hide();
		                    $('.step1').fadeIn("slow")
    				});
    		                    });				
                </script>

    </body>
</html>